//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmCaller.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.AlgorithmsWebServiceSoap")]
    public interface AlgorithmsWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        int Sum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name ar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SimpleArraySum", ReplyAction="*")]
        AlgorithmCaller.ServiceReference1.SimpleArraySumResponse SimpleArraySum(AlgorithmCaller.ServiceReference1.SimpleArraySumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SimpleArraySum", ReplyAction="*")]
        System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.SimpleArraySumResponse> SimpleArraySumAsync(AlgorithmCaller.ServiceReference1.SimpleArraySumRequest request);
        
        // CODEGEN: Generating message contract since element name firstGroup from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompareTheTriplets", ReplyAction="*")]
        AlgorithmCaller.ServiceReference1.CompareTheTripletsResponse CompareTheTriplets(AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompareTheTriplets", ReplyAction="*")]
        System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.CompareTheTripletsResponse> CompareTheTripletsAsync(AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest request);
        
        // CODEGEN: Generating message contract since element name a from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiagonalDifference", ReplyAction="*")]
        AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponse DiagonalDifference(AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiagonalDifference", ReplyAction="*")]
        System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponse> DiagonalDifferenceAsync(AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StairCase", ReplyAction="*")]
        void StairCase(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StairCase", ReplyAction="*")]
        System.Threading.Tasks.Task StairCaseAsync(int n);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SimpleArraySumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SimpleArraySum", Namespace="http://tempuri.org/", Order=0)]
        public AlgorithmCaller.ServiceReference1.SimpleArraySumRequestBody Body;
        
        public SimpleArraySumRequest() {
        }
        
        public SimpleArraySumRequest(AlgorithmCaller.ServiceReference1.SimpleArraySumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SimpleArraySumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlgorithmCaller.ServiceReference1.ArrayOfInt ar;
        
        public SimpleArraySumRequestBody() {
        }
        
        public SimpleArraySumRequestBody(AlgorithmCaller.ServiceReference1.ArrayOfInt ar) {
            this.ar = ar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SimpleArraySumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SimpleArraySumResponse", Namespace="http://tempuri.org/", Order=0)]
        public AlgorithmCaller.ServiceReference1.SimpleArraySumResponseBody Body;
        
        public SimpleArraySumResponse() {
        }
        
        public SimpleArraySumResponse(AlgorithmCaller.ServiceReference1.SimpleArraySumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SimpleArraySumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SimpleArraySumResult;
        
        public SimpleArraySumResponseBody() {
        }
        
        public SimpleArraySumResponseBody(int SimpleArraySumResult) {
            this.SimpleArraySumResult = SimpleArraySumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompareTheTripletsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompareTheTriplets", Namespace="http://tempuri.org/", Order=0)]
        public AlgorithmCaller.ServiceReference1.CompareTheTripletsRequestBody Body;
        
        public CompareTheTripletsRequest() {
        }
        
        public CompareTheTripletsRequest(AlgorithmCaller.ServiceReference1.CompareTheTripletsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CompareTheTripletsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlgorithmCaller.ServiceReference1.ArrayOfInt firstGroup;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlgorithmCaller.ServiceReference1.ArrayOfInt secondGroup;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sizeOfArray;
        
        public CompareTheTripletsRequestBody() {
        }
        
        public CompareTheTripletsRequestBody(AlgorithmCaller.ServiceReference1.ArrayOfInt firstGroup, AlgorithmCaller.ServiceReference1.ArrayOfInt secondGroup, int sizeOfArray) {
            this.firstGroup = firstGroup;
            this.secondGroup = secondGroup;
            this.sizeOfArray = sizeOfArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompareTheTripletsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompareTheTripletsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AlgorithmCaller.ServiceReference1.CompareTheTripletsResponseBody Body;
        
        public CompareTheTripletsResponse() {
        }
        
        public CompareTheTripletsResponse(AlgorithmCaller.ServiceReference1.CompareTheTripletsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CompareTheTripletsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlgorithmCaller.ServiceReference1.ArrayOfInt CompareTheTripletsResult;
        
        public CompareTheTripletsResponseBody() {
        }
        
        public CompareTheTripletsResponseBody(AlgorithmCaller.ServiceReference1.ArrayOfInt CompareTheTripletsResult) {
            this.CompareTheTripletsResult = CompareTheTripletsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DiagonalDifferenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DiagonalDifference", Namespace="http://tempuri.org/", Order=0)]
        public AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequestBody Body;
        
        public DiagonalDifferenceRequest() {
        }
        
        public DiagonalDifferenceRequest(AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DiagonalDifferenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlgorithmCaller.ServiceReference1.ArrayOfInt[] a;
        
        public DiagonalDifferenceRequestBody() {
        }
        
        public DiagonalDifferenceRequestBody(AlgorithmCaller.ServiceReference1.ArrayOfInt[] a) {
            this.a = a;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DiagonalDifferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DiagonalDifferenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponseBody Body;
        
        public DiagonalDifferenceResponse() {
        }
        
        public DiagonalDifferenceResponse(AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DiagonalDifferenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DiagonalDifferenceResult;
        
        public DiagonalDifferenceResponseBody() {
        }
        
        public DiagonalDifferenceResponseBody(int DiagonalDifferenceResult) {
            this.DiagonalDifferenceResult = DiagonalDifferenceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlgorithmsWebServiceSoapChannel : AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlgorithmsWebServiceSoapClient : System.ServiceModel.ClientBase<AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap>, AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap {
        
        public AlgorithmsWebServiceSoapClient() {
        }
        
        public AlgorithmsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlgorithmsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sum(int a, int b) {
            return base.Channel.Sum(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int a, int b) {
            return base.Channel.SumAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlgorithmCaller.ServiceReference1.SimpleArraySumResponse AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap.SimpleArraySum(AlgorithmCaller.ServiceReference1.SimpleArraySumRequest request) {
            return base.Channel.SimpleArraySum(request);
        }
        
        public int SimpleArraySum(AlgorithmCaller.ServiceReference1.ArrayOfInt ar) {
            AlgorithmCaller.ServiceReference1.SimpleArraySumRequest inValue = new AlgorithmCaller.ServiceReference1.SimpleArraySumRequest();
            inValue.Body = new AlgorithmCaller.ServiceReference1.SimpleArraySumRequestBody();
            inValue.Body.ar = ar;
            AlgorithmCaller.ServiceReference1.SimpleArraySumResponse retVal = ((AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap)(this)).SimpleArraySum(inValue);
            return retVal.Body.SimpleArraySumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.SimpleArraySumResponse> AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap.SimpleArraySumAsync(AlgorithmCaller.ServiceReference1.SimpleArraySumRequest request) {
            return base.Channel.SimpleArraySumAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.SimpleArraySumResponse> SimpleArraySumAsync(AlgorithmCaller.ServiceReference1.ArrayOfInt ar) {
            AlgorithmCaller.ServiceReference1.SimpleArraySumRequest inValue = new AlgorithmCaller.ServiceReference1.SimpleArraySumRequest();
            inValue.Body = new AlgorithmCaller.ServiceReference1.SimpleArraySumRequestBody();
            inValue.Body.ar = ar;
            return ((AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap)(this)).SimpleArraySumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlgorithmCaller.ServiceReference1.CompareTheTripletsResponse AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap.CompareTheTriplets(AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest request) {
            return base.Channel.CompareTheTriplets(request);
        }
        
        public AlgorithmCaller.ServiceReference1.ArrayOfInt CompareTheTriplets(AlgorithmCaller.ServiceReference1.ArrayOfInt firstGroup, AlgorithmCaller.ServiceReference1.ArrayOfInt secondGroup, int sizeOfArray) {
            AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest inValue = new AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest();
            inValue.Body = new AlgorithmCaller.ServiceReference1.CompareTheTripletsRequestBody();
            inValue.Body.firstGroup = firstGroup;
            inValue.Body.secondGroup = secondGroup;
            inValue.Body.sizeOfArray = sizeOfArray;
            AlgorithmCaller.ServiceReference1.CompareTheTripletsResponse retVal = ((AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap)(this)).CompareTheTriplets(inValue);
            return retVal.Body.CompareTheTripletsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.CompareTheTripletsResponse> AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap.CompareTheTripletsAsync(AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest request) {
            return base.Channel.CompareTheTripletsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.CompareTheTripletsResponse> CompareTheTripletsAsync(AlgorithmCaller.ServiceReference1.ArrayOfInt firstGroup, AlgorithmCaller.ServiceReference1.ArrayOfInt secondGroup, int sizeOfArray) {
            AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest inValue = new AlgorithmCaller.ServiceReference1.CompareTheTripletsRequest();
            inValue.Body = new AlgorithmCaller.ServiceReference1.CompareTheTripletsRequestBody();
            inValue.Body.firstGroup = firstGroup;
            inValue.Body.secondGroup = secondGroup;
            inValue.Body.sizeOfArray = sizeOfArray;
            return ((AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap)(this)).CompareTheTripletsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponse AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap.DiagonalDifference(AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest request) {
            return base.Channel.DiagonalDifference(request);
        }
        
        public int DiagonalDifference(AlgorithmCaller.ServiceReference1.ArrayOfInt[] a) {
            AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest inValue = new AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest();
            inValue.Body = new AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequestBody();
            inValue.Body.a = a;
            AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponse retVal = ((AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap)(this)).DiagonalDifference(inValue);
            return retVal.Body.DiagonalDifferenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponse> AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap.DiagonalDifferenceAsync(AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest request) {
            return base.Channel.DiagonalDifferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlgorithmCaller.ServiceReference1.DiagonalDifferenceResponse> DiagonalDifferenceAsync(AlgorithmCaller.ServiceReference1.ArrayOfInt[] a) {
            AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest inValue = new AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequest();
            inValue.Body = new AlgorithmCaller.ServiceReference1.DiagonalDifferenceRequestBody();
            inValue.Body.a = a;
            return ((AlgorithmCaller.ServiceReference1.AlgorithmsWebServiceSoap)(this)).DiagonalDifferenceAsync(inValue);
        }
        
        public void StairCase(int n) {
            base.Channel.StairCase(n);
        }
        
        public System.Threading.Tasks.Task StairCaseAsync(int n) {
            return base.Channel.StairCaseAsync(n);
        }
    }
}
